import { LocationMode, Mood, Scene } from './quest.enums';
import { Quest } from './quest.entity';

export const INITIAL_QUESTS: Array<Partial<Quest>> = [
  {
    mood: Mood.RELAXED,
    title: '去花城广场看一次城市天际线',
    durationMinutes: 30,
    distanceLabel: '广州城内',
    scene: Scene.OUTDOOR,
    settingLabel: '适合独自',
    prompt: '慢慢走过广场，找一个能同时看到广州塔和城市灯光的位置。',
    locationMode: LocationMode.FIXED,
    cityAdcode: '440100',
    fixedLongitude: 113.322,
    fixedLatitude: 23.1197,
    fixedLocationName: '花城广场',
    unlockRadiusM: 50000,
    completionRadiusM: 500,
    sortOrder: 1,
  },
  {
    mood: Mood.FRESH,
    title: '走进越秀公园，找一段有树荫的路',
    durationMinutes: 40,
    distanceLabel: '广州城内',
    scene: Scene.OUTDOOR,
    settingLabel: '适合独自',
    prompt: '不用赶往某个景点，沿着让你舒服的方向走二十分钟。',
    locationMode: LocationMode.FIXED,
    cityAdcode: '440100',
    fixedLongitude: 113.2644,
    fixedLatitude: 23.1374,
    fixedLocationName: '越秀公园',
    unlockRadiusM: 50000,
    completionRadiusM: 600,
    sortOrder: 2,
  },
  {
    mood: Mood.COMPANY,
    title: '到沙面岛散步，选一栋喜欢的老建筑',
    durationMinutes: 45,
    distanceLabel: '广州城内',
    scene: Scene.OUTDOOR,
    settingLabel: '适合结伴',
    prompt: '留意门窗、树影和墙面的颜色，拍下最打动你的一个细节。',
    locationMode: LocationMode.FIXED,
    cityAdcode: '440100',
    fixedLongitude: 113.2398,
    fixedLatitude: 23.109,
    fixedLocationName: '沙面岛',
    unlockRadiusM: 50000,
    completionRadiusM: 600,
    sortOrder: 3,
  },
  {
    mood: Mood.FRESH,
    title: '发现东山口藏在街巷里的旧时光',
    durationMinutes: 30,
    distanceLabel: '隐藏地点',
    scene: Scene.OUTDOOR,
    settingLabel: '等待发现',
    prompt: '靠近后才会显露，留意红砖墙、旧窗台和转角的小店。',
    locationMode: LocationMode.FIXED,
    cityAdcode: '440100',
    fixedLongitude: 113.2942,
    fixedLatitude: 23.126,
    fixedLocationName: '东山口街区',
    unlockRadiusM: 300,
    completionRadiusM: 250,
    isHidden: true,
    sortOrder: 4,
  },
  {
    mood: Mood.RELAXED,
    title: '去附近公园，听十分钟风声',
    durationMinutes: 20,
    distanceLabel: '约620米',
    scene: Scene.OUTDOOR,
    settingLabel: '适合独自',
    prompt: '不戴耳机，听树叶、脚步和城市远处的声音。',
    locationMode: LocationMode.FIXED,
    cityAdcode: '330100',
    fixedLongitude: 120.1572,
    fixedLatitude: 30.2594,
    fixedLocationName: '太子湾公园',
    unlockRadiusM: 5000,
    completionRadiusM: 500,
    sortOrder: 1,
  },
  {
    mood: Mood.FRESH,
    title: '沿着河边走一段，找一座喜欢的桥',
    durationMinutes: 30,
    distanceLabel: '约560米',
    scene: Scene.OUTDOOR,
    settingLabel: '适合独自',
    prompt: '慢一点走，看看水面、桥影和来往的人。',
    locationMode: LocationMode.FIXED,
    cityAdcode: '330100',
    fixedLongitude: 120.1454,
    fixedLatitude: 30.2575,
    fixedLocationName: '河边长椅',
    completionRadiusM: 500,
    sortOrder: 2,
  },
  {
    mood: Mood.COMPANY,
    title: '找一家附近的咖啡馆，给朋友写张明信片',
    durationMinutes: 40,
    distanceLabel: '附近',
    scene: Scene.INDOOR,
    settingLabel: '适合独自',
    prompt: '不用写很多，只记下今天最想分享的一件小事。',
    locationMode: LocationMode.POI_TYPE,
    poiType: '050500',
    unlockRadiusM: 5000,
    completionRadiusM: 300,
    sortOrder: 3,
  },
  {
    mood: Mood.FRESH,
    title: '找到藏在街角的一处安静庭院',
    durationMinutes: 30,
    distanceLabel: '隐藏地点',
    scene: Scene.OUTDOOR,
    settingLabel: '等待发现',
    prompt: '靠近后它才会显露，留意旧墙边的树影。',
    locationMode: LocationMode.FIXED,
    cityAdcode: '330100',
    fixedLongitude: 120.1518,
    fixedLatitude: 30.2548,
    fixedLocationName: '街角庭院',
    unlockRadiusM: 300,
    completionRadiusM: 200,
    isHidden: true,
    sortOrder: 4,
  },
  {
    mood: Mood.FRESH,
    title: '去一条没走过的街，\n拍下三个蓝色物件',
    durationMinutes: 20,
    distanceLabel: '600米',
    scene: Scene.OUTDOOR,
    settingLabel: '适合独自',
    prompt: '不用走得很远，只要离开熟悉的路线一小会儿。',
    sortOrder: 10,
  },
  {
    mood: Mood.FRESH,
    title: '走进一家从未去过的小店，\n挑一样有趣的小物',
    durationMinutes: 20,
    distanceLabel: '附近',
    scene: Scene.ANY,
    settingLabel: '适合独自',
    prompt: '不必购买贵重物品，重点是发现日常之外的新东西。',
    sortOrder: 11,
  },
  {
    mood: Mood.FRESH,
    title: '换一条回家的路线，\n记住沿途最特别的招牌',
    durationMinutes: 60,
    distanceLabel: '附近',
    scene: Scene.OUTDOOR,
    settingLabel: '适合独自',
    prompt: '让熟悉的城市在今天变得陌生一点。',
    sortOrder: 12,
  },
  {
    mood: Mood.RELAXED,
    title: '找一块有风的地方，\n安静地坐十分钟',
    durationMinutes: 20,
    distanceLabel: '附近',
    scene: Scene.OUTDOOR,
    settingLabel: '适合独自',
    prompt: '不戴耳机，听听这座城市此刻的声音。',
    sortOrder: 20,
  },
  {
    mood: Mood.RELAXED,
    title: '泡一杯喜欢的饮品，\n什么也不做地喝完它',
    durationMinutes: 20,
    distanceLabel: '室内',
    scene: Scene.INDOOR,
    settingLabel: '适合独自',
    prompt: '把注意力交给温度、气味和入口的味道。',
    sortOrder: 21,
  },
  {
    mood: Mood.RELAXED,
    title: '关掉所有通知，\n慢慢整理一个小角落',
    durationMinutes: 60,
    distanceLabel: '室内',
    scene: Scene.INDOOR,
    settingLabel: '适合独自',
    prompt: '只整理一个抽屉或一小块桌面就足够。',
    sortOrder: 22,
  },
  {
    mood: Mood.ACHIEVEMENT,
    title: '完成一件拖了很久的，\n五分钟小事',
    durationMinutes: 5,
    distanceLabel: '随地',
    scene: Scene.ANY,
    settingLabel: '适合独自',
    prompt: '只做最小的第一步，做完就算胜利。',
    sortOrder: 30,
  },
  {
    mood: Mood.ACHIEVEMENT,
    title: '列出今天最重要的一件事，\n现在专注二十分钟',
    durationMinutes: 20,
    distanceLabel: '随地',
    scene: Scene.ANY,
    settingLabel: '适合独自',
    prompt: '不要列长清单，只完成最重要的那一件。',
    sortOrder: 31,
  },
  {
    mood: Mood.ACHIEVEMENT,
    title: '学会一个一直好奇的小技能，\n留下你的第一份成果',
    durationMinutes: 60,
    distanceLabel: '随地',
    scene: Scene.ANY,
    settingLabel: '适合独自',
    prompt: '不追求熟练，只需要做出第一个可以看见的结果。',
    sortOrder: 32,
  },
  {
    mood: Mood.COMPANY,
    title: '给一个想到的人，\n发一句真诚的问候',
    durationMinutes: 5,
    distanceLabel: '线上',
    scene: Scene.ONLINE,
    settingLabel: '可结伴',
    prompt: '不需要寒暄，只说你真正想说的那句话。',
    sortOrder: 40,
  },
  {
    mood: Mood.COMPANY,
    title: '邀请一个朋友，\n一起散步二十分钟',
    durationMinutes: 20,
    distanceLabel: '附近',
    scene: Scene.OUTDOOR,
    settingLabel: '需要伙伴',
    prompt: '不设目的地，边走边聊最近发生的小事。',
    sortOrder: 41,
  },
  {
    mood: Mood.COMPANY,
    title: '和家人一起准备一顿饭，\n认真吃完再收拾',
    durationMinutes: 60,
    distanceLabel: '室内',
    scene: Scene.INDOOR,
    settingLabel: '适合家人',
    prompt: '把分工、等待和分享都当成今天的故事。',
    sortOrder: 42,
  },
];
